using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SourceGenerator.Utils;
using System.Text;

namespace SourceGenerator;

[Generator]
public sealed class AutoImplementGenerator : IIncrementalGenerator
{
    private record ClassModel(string Name, string NameSpace, EquatableList<InterfaceModel> Interfaces);
    private record InterfaceModel(string FullyQualifiedName, EquatableList<string> Properties);
    private const string AttributeNameSpace = "AttributeGenerator";
    private const string AttributeName = "AutomImplementProperties";
    private const string AttributeClassName = $"{AttributeName}Attribute";
    private const string FullyQualifiedAttributeName = $"{AttributeNameSpace}.{AttributeClassName}";
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource($"{AttributeClassName}.g.cs", $$"""
            // <auto-generated/>
            namespace {{AttributeNameSpace}};
            [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            sealed class {{AttributeClassName}} : Attribute
            {
                public Type[] InterfaceTypes { get; }
                public {{AttributeClassName}}(params Type[] interfaceTypes)
                {
                    InterfaceTypes = interfaceTypes;
                }
            }
            """);
        });

        // ForAttributeWithMetadataName è fino al 99% più veloce di CreateSyntaxProvider
        IncrementalValuesProvider<ClassModel> provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: FullyQualifiedAttributeName,
            predicate: static (node, cancenationToken) => node is ClassDeclarationSyntax,
            transform: static (ctx, cancenationToken) =>
            {
                ISymbol classSymbol = ctx.TargetSymbol;

                EquatableList<InterfaceModel> interfaceModels = GetInterfaceModels(ctx.Attributes[0]);
                return new ClassModel(classSymbol.Name, classSymbol.ContainingNamespace.ToDisplayString(), interfaceModels);
            });

        context.RegisterSourceOutput(provider, static (context, classModel) =>
        {
            foreach (InterfaceModel interfaceModel in classModel.Interfaces)
            {
                StringBuilder sb = new($$"""
                    // <auto-generated/>
                    namespace {{classModel.NameSpace}};
                    internal partial class {{classModel.Name}} : {{interfaceModel.FullyQualifiedName}} // auto-generated {{AttributeName}}
                    {

                    """);

                foreach (string property in interfaceModel.Properties)
                    sb.AppendLine(property);

                sb.AppendLine("""
                    }
                    """);

                //Concat class name and interface name to have unique file name if a class implements two interfaces with AutoImplement Attribute
                string generatedFileName = $"{classModel.Name}_{interfaceModel.FullyQualifiedName.ToString().Split('.').GetLast()}.g.cs";
                context.AddSource(generatedFileName, sb.ToString());
            }
        });
    }

    private static EquatableList<InterfaceModel> GetInterfaceModels(AttributeData attribute)
    {
        EquatableList<InterfaceModel> interfaceModelList = [];

        if (attribute.ConstructorArguments.Length == 0)
            return interfaceModelList;

        foreach (TypedConstant constructorArgumentValue in attribute.ConstructorArguments[0].Values)
        {
            if (constructorArgumentValue.Value is not INamedTypeSymbol { TypeKind: TypeKind.Interface } interfaceSymbol)
                continue;

            EquatableList<string> properties = [];
            foreach (IPropertySymbol interfaceProperty in interfaceSymbol.GetMembers().OfType<IPropertySymbol>())
            {
                string type = interfaceProperty.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                // Check if property has a setter
                string setter = interfaceProperty.SetMethod is null
                    ? string.Empty
                    : "set; ";

                properties.Add($$"""
                        public {{type}} {{interfaceProperty.Name}} { get; {{setter}}}
                    """);
            }

            interfaceModelList.Add(new InterfaceModel(interfaceSymbol.ToDisplayString(), properties));
        }

        return interfaceModelList;
    }
}
