using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SourceGenerator.Utils;
using System.Linq;
using System.Text;

namespace SourceGenerator;

[Generator]
public sealed class EnhancedRepository : IIncrementalGenerator
{
    private record ClassModel(string Name, string NameSpace, string GenericEntity, string GenericFilter);
    private record InterfaceModel(string FullyQualifiedName, EquatableList<string> Properties);
    private const string InterfaceName = "IGenericRepository";
    private const string AttributeNameSpace = "AttributeGenerator";
    private const string AttributeName = "EnhancedRepository";
    private const string AttributeClassName = $"{AttributeName}Attribute";
    private const string FullyQualifiedAttributeName = $"{AttributeNameSpace}.{AttributeClassName}";
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource($"{AttributeClassName}.g.cs", $$"""
            // <auto-generated/>
            namespace {{AttributeNameSpace}};
            [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            sealed class {{AttributeClassName}} : Attribute
            {
                public {{AttributeClassName}}()
                {
                }
            }
            """);
        });

        IncrementalValuesProvider<ClassModel?> provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: FullyQualifiedAttributeName,
            predicate: static (node, cancenationToken) => node is ClassDeclarationSyntax,
            transform: static (ctx, cancenationToken) =>
            {
                ISymbol classSymbol = ctx.TargetSymbol;
                INamedTypeSymbol classSymbol1 = (INamedTypeSymbol)classSymbol;
                INamedTypeSymbol? interfaceSymbol = classSymbol1.AllInterfaces.FirstOrDefault(x => x.Name == InterfaceName && x.TypeArguments.Length > 1);
                if (interfaceSymbol is null)
                    return null;

                string genericEntity = interfaceSymbol.TypeArguments[0].ToString();
                string genericFilter = interfaceSymbol.TypeArguments[1].ToString();
                return new ClassModel(classSymbol.Name, classSymbol.ContainingNamespace.ToDisplayString(), genericEntity, genericFilter);
            });

        context.RegisterSourceOutput(provider, static (context, classModel) =>
        {
            if (classModel is null)
                return;
            string shortEntityClassName = classModel.GenericEntity.Split('.').Last();
            context.AddSource($"{classModel.Name}.g.cs", $$"""
                // <auto-generated/>
                #nullable enable
                namespace {{classModel.NameSpace}};

                internal partial class {{classModel.Name}} // auto-generated {{AttributeName}}
                {
                    public {{classModel.GenericEntity}}? FirstOrDefault({{classModel.GenericFilter}} filter)
                    {
                        return GetQueryable(filter).FirstOrDefault();
                    }
                }
            """);
        });
    }
}
