using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SourceGenerator.Utils;
using System.Linq;
using System.Text;

namespace SourceGenerator
{
    //Decoratore per fare sì che questa classe venga riconosciuta come generatore
    [Generator]
    public class ExceptionCodeGenerator : IIncrementalGenerator
    /*
    È meglio utilizzare IIncrementalGenerator invece del vecchio IGenerator
    È più efficiente utilizzando un meccanismo di cache per rilanciare i generatori durante lo sviluppo solo quando necessario
    Questo perché se di base i Source Generators vengono lanciati solo in fase di compilazione
    Gli IDE li lanciano di continuo perché lo sviluppatore possa vederli in tempo reale
    Il fatto che venissero lanciati più volte al secondo peggiorava drasticamente le performance degli IDE
    Vedremo i principali modi in cui questo problema è stato mitigato
    */
    {
        // È importante che questi modelli siano record e che non venga fatto ReferenceEquals ai fini della cache
        // Idem per ogni property dei record
        private record EnumDeclarationModel(EquatableList<EnumMemberModel> Members);
        private record EnumMemberModel(string Name, string Description);
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            //if (!Debugger.IsAttached)
            //    Debugger.Launch();

            const string enumName = "ExceptionCode";
            IncrementalValuesProvider<EnumDeclarationModel> provider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (node, cancellationToken) => node is EnumDeclarationSyntax enumDeclaration && enumDeclaration.Identifier.ValueText == enumName,
                transform: (ctx, cancellationToken) =>
                {
                    EnumDeclarationSyntax enumDeclaration = ctx.Node as EnumDeclarationSyntax;
                    EquatableList<EnumMemberModel> members = [];
                    foreach (MemberDeclarationSyntax element in enumDeclaration.Members)
                    {
                        if (element is not EnumMemberDeclarationSyntax enumMember)
                            continue;
                        if (TryGetDescription(enumMember.AttributeLists, out string description))
                            members.Add(new EnumMemberModel(enumMember.Identifier.ValueText, description));
                    }

                    return new EnumDeclarationModel(members);
                });

            //RegisterSourceOutput accetta in ingresso il provider, per ogni elemento emesso dal provider parte un trigger solo se non risulta uguale ad un elemento presente in cache
            context.RegisterSourceOutput(provider, static (context, syntax) =>
            {
                StringBuilder errorManager = new();
                StringBuilder getExceptionBase = new();
                StringBuilder getMessage = new();

                foreach (EnumMemberModel element in syntax.Members)
                {
                    string exceptionName = $"{element.Description}Exception";
                    //Sia l'estensione del file .g.cs che la prima riga // <auto-generated/> sono convenzioni per indicare che un file è stato generato in automatico 
                    context.AddSource($"{element.Name}_{exceptionName}.g.cs", $$"""
                        // <auto-generated/>
                        namespace ConsoleApp.Errors;
                        #nullable enable
                        /// <summary
                        /// {{element.Name}}
                        /// </summary>
                        public class {{exceptionName}} : BaseException
                        {
                            public {{exceptionName}}(string message) : base(message, null) { }
                            public {{exceptionName}}(string message, Guid? errorId) : base(message, errorId) { }
                            public {{exceptionName}}(Exception exception) : base(exception) { }
                            public override ExceptionCode ExceptionCode => ExceptionCode.{{element.Name}};
                            public static string GetExceptionCodeDescription() => "{{element.Description}}";
                            public override string ExceptionCodeDescription => GetExceptionCodeDescription();
                        }
                        """);

                    errorManager.Append($$"""
                            /// <summary
                            /// {{element.Name}}
                            /// </summary>
                            public static {{exceptionName}} {{element.Description}}Error(string message)
                            {
                                return new {{exceptionName}}(message);
                            }

                        """);

                    getExceptionBase.AppendLine($"              ExceptionCode.{element.Name} => new {exceptionName}(message, errorId),");

                    getMessage.AppendLine($"""
                                                ExceptionCode.{element.Name} => "{element.Description}",
                                  """);
                        
                }

                if (errorManager.Length == 0)
                    return;

                context.AddSource("ErrorManager.g.cs", $$"""
                    // <auto-generated/>
                    namespace ConsoleApp.Errors;
                    
                    public static partial class ErrorManager
                    {
                    {{errorManager}}

                        public static BaseException GetBaseException(string message, ExceptionCode exceptionCode, Guid? errorId = null)
                        {
                            return exceptionCode switch
                            {
                    {{getExceptionBase}}
                                _ => throw new Exception("Unsupported ExceptionCode"),
                            };
                        }
                    
                        public static string GetMessage(ExceptionCode exceptionCode)
                        {
                            return exceptionCode switch
                            {
                    {{getMessage}}
                                _ => throw new Exception("Unsupported ExceptionCode"),
                            };
                        }

                    }
                    """);
            });
        }

        private static bool TryGetDescription(SyntaxList<AttributeListSyntax> attributesLists, out string description)
        {
            if (TryGetArguments(attributesLists, out string[] arguments) && arguments.Length > 0)
            {
                description = arguments[0].Replace("\"", string.Empty);
                return true;
            }

            description = string.Empty;
            return false;
        }
        private const string attributeName = "Description";
        private static bool TryGetArguments(SyntaxList<AttributeListSyntax> attributesLists, out string[] arguments)
        {
            foreach (AttributeListSyntax attributeList in attributesLists.Where(x => x.ToString().Contains(attributeName)))
                if (TryGetArguments(attributeList, out arguments))
                    return true;

            arguments = [];
            return false;
        }
        private static bool TryGetArguments(AttributeListSyntax attributeLists, out string[] arguments)
        {
            arguments = [];
            AttributeSyntax? attribute = attributeLists.Attributes.FirstOrDefault(x => x.ToString().Contains(attributeName));
            if (attribute?.ArgumentList is null)
                return false;

            arguments = [.. attribute.ArgumentList.Arguments
                .Select(x => x.Expression.ToString())
                .Where(x => !string.IsNullOrWhiteSpace(x))];
            return true;
        }
    }
}
